apiVersion: k8s.otterize.com/v1alpha1
kind: ClientIntents
metadata:
  name: client
  namespace:  otterize-tutorial-kafka-mtls-intents
spec:
  service:
    name: client
  calls:
    - name: kafka
      namespace: kafka
      type: Kafka
      topics:
        - name: mytopic
          operation: all
