apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
#        to rename credentials-secret-name
        otterize/tls-secret-name: client-credentials-secret
        otterize/cert-ttl: "2592000"
    spec:
      containers:
        - name: client
          image: broadinstitute/python-requests
          command: [ "/bin/sh", "-c", "--" ]
          args: [ " while true; do python /app/client.py; sleep 2; done;" ]
          volumeMounts:
            - mountPath: /app/
              name: client-py
            - name: otterize-credentials
              mountPath: /var/otterize/credentials
              readOnly: true
      volumes:
        - name: client-py
          configMap:
            name: client-py
        - name: otterize-credentials
          secret:
            secretName: client-credentials-secret