apiVersion: v1
kind: Namespace
metadata:
  name: otterize-tutorial-mtls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-py
  namespace: otterize-tutorial-mtls
data:
  client.py: |
    import requests
  
    resp = requests.get("https://server.otterize-tutorial-mtls/hello",
        cert=('/etc/otterize/svid.pem', '/etc/otterize/key.pem'),
        verify="/etc/otterize/bundle.pem")
    print(resp.text)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: otterize-tutorial-mtls
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
#        to rename credentials-secret-name
        otterize/tls-secret-name: client-credentials-secret
        otterize/cert-ttl: "2592000"
    spec:
      containers:
        - name: client
          image: broadinstitute/python-requests
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "trap : TERM INT; sleep infinity & wait" ]
          volumeMounts:
            - mountPath: /app/
              name: client-py
            - name: otterize-credentials
              mountPath: /etc/otterize
              readOnly: true
      volumes:
        - name: client-py
          configMap:
            name: client-py
        - name: otterize-credentials
          secret:
            secretName: client-credentials-secret