apiVersion: v1
kind: ConfigMap
metadata:
  name: interactive-properties
  namespace: ibac-for-kafka
data:
  client.properties: |
    security.protocol=SSL
    ssl.keystore.location=/var/otterize/credentials/kafka.keystore.jks
    ssl.keystore.password=password
    ssl.truststore.location=/var/otterize/credentials/kafka.truststore.jks
    ssl.truststore.password=password