apiVersion: v1
kind: Namespace
metadata:
  name: otterize-demo-mapper
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: otterize-demo-mapper
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80