superUsers: "User:CN=kafka.kafka,O=SPIRE,C=US;User:CN=intents-operator-controller-manager.otterize,O=SPIRE,C=US"
livenessProbe:
  initialDelaySeconds: 20
readinessProbe:
  initialDelaySeconds: 20
listeners:
  - "CLIENT://:9092"
  - "INTERNAL://:9093"
advertisedListeners:
  - "CLIENT://:9092"
  - "INTERNAL://:9093"
listenerSecurityProtocolMap: "INTERNAL:SSL,CLIENT:SSL"
auth:
  clientProtocol: mtls
  interBrokerProtocol: mtls
  tls:
    type: jks
    existingSecrets:
      - kafka-tls-secret
    password: password
authorizerClassName: kafka.security.authorizer.AclAuthorizer
podAnnotations:
  spire-integration.otterize.com/cert-type: jks
  spire-integration.otterize.com/tls-secret-name: kafka-tls-secret
  spire-integration.otterize.com/truststore-file-name: kafka.truststore.jks
  spire-integration.otterize.com/keystore-file-name: kafka-keystore.jks
  spire-integration.otterize.com/dns-names: "kafka-0.kafka-headless.kafka.svc.cluster.local,kafka.kafka.svc.cluster.local"
  spire-integration.otterize.com/cert-ttl: "31536000" # 1 year
resources:
  requests:
    cpu: 50m
    memory: 256Mi
