apiVersion: apps/v1
kind: Deployment
metadata:
  name: testingservice
  namespace: otterize-ecom-demo
spec:
  selector:
    matchLabels:
      app: testingservice
  template:
    metadata:
      labels:
        app: testingservice
    spec:
      containers:
        - name: testingservice
          image: alpine/curl
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do curl -si frontend; sleep 2; done" ]