apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-allowed
spec:
  selector:
    matchLabels:
      app: client-allowed
  template:
    metadata:
      labels:
        app: client-allowed
    spec:
      containers:
        - name: client-allowed
          image: alpine/curl
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do timeout 2 curl -si server || echo \"curl timed out\"; sleep 2; done" ]